// Raio-X Político - Propostas Legislativas Reais Curadas
// 3 propostas autênticas para cada um dos 15 parlamentares federais da 57ª Legislatura

const REAL_PROPOSALS = {
  'cand-tabata-amaral': [
    {
      id: 'prop-tabata-1',
      title: 'Poupança do Ensino Médio (Programa Pé-de-Meia)',
      category: 'Educação',
      score: 9.4,
      summary: 'Incentivo financeiro mensal e poupança de formatura para estudantes de baixa renda da rede pública para erradicar a evasão escolar.',
      problemStatement: 'Mais de 500 mil jovens abandonam o ensino médio anualmente no Brasil por necessidade urgente de complementar renda familiar.',
      solutionDetails: 'Depósito mensal de R$ 200 condicionado a 80% de frequência escolar e bônus de R$ 1.000 ao fim de cada ano letivo concluído com aprovação.',
      budgetAndCost: 'R$ 7.1 bilhões / ano (Fundos Federais)',
      timeline: '2024 - 2026',
      pros: 'Queda estimada de até 40% na evasão escolar em periferias.',
      cons: 'Exige coordenação rigorosa entre estados e Caixa Econômica Federal.',
      supportVotes: 1420,
      rejectVotes: 88
    },
    {
      id: 'prop-tabata-2',
      title: 'Conectividade e Internet 5G em 100% das Escolas Públicas',
      category: 'Tecnologia',
      score: 9.1,
      summary: 'Utilização obrigatória dos recursos do FUST para equipar escolas públicas com banda larga ultraveloz e laboratórios digitais.',
      problemStatement: 'Abismo digital entre escolas particulares e estaduais periféricas agrava a desigualdade de oportunidades.',
      solutionDetails: 'Desbloqueio de verbas do FUST com fiscalização do TCU para instalação de antenas 5G e tablets pedagógicos.',
      budgetAndCost: 'R$ 3.2 bilhões (FUST)',
      timeline: '36 meses',
      pros: 'Capacitação digital precoce para o mercado tech.',
      cons: 'Dificuldade logística em escolas rurais e isoladas.',
      supportVotes: 1180,
      rejectVotes: 45
    },
    {
      id: 'prop-tabata-3',
      title: 'Marco Legal da Primeira Infância e Creches Noturnas',
      category: 'Assistência Social',
      score: 8.8,
      summary: 'Ampliação do atendimento em creches municipais com horários flexíveis para mães que trabalham em turnos noturnos ou estudam.',
      problemStatement: 'Mães solo são as mais penalizadas pelo desemprego por falta de vagas em creches fora do horário comercial padrão.',
      solutionDetails: 'Repasses federais vinculados ao Fundeb para municípios que criarem creches polo com horário estendido até 22h.',
      budgetAndCost: 'R$ 1.8 bilhão / ano',
      timeline: '24 meses',
      pros: 'Aumento da empregabilidade feminina e proteção integral infantil.',
      cons: 'Custo adicional de pessoal pedagógico em regime de escala.',
      supportVotes: 960,
      rejectVotes: 72
    }
  ],
  'cand-kim-kataguiri': [
    {
      id: 'prop-kim-1',
      title: 'Extinção dos Supersalários e Penduricalhos no Serviço Público',
      category: 'Economia',
      score: 9.6,
      summary: 'Aplicação rígida e irrestrita do teto constitucional (STF) a todas as verbas indenizatórias, auxílios e gratificações de magistrados e procuradores.',
      problemStatement: 'Penduricalhos criam vencimentos superiores a R$ 100 mil mensais, custando bilhões e gerando injustiça cívica.',
      solutionDetails: 'Enquadramento de todas as parcelas indenizatórias contínuas no abate-teto com responsabilização direta por improbidade.',
      budgetAndCost: 'Economia estimada de R$ 5.8 bilhões / ano',
      timeline: 'Imediato',
      pros: 'Justiça orçamentária e corte expressivo de privilégios corporativistas.',
      cons: 'Forte resistência e judicialização de entidades de classe.',
      supportVotes: 2310,
      rejectVotes: 115
    },
    {
      id: 'prop-kim-2',
      title: 'Marco Legal da Liberdade Econômica e Desregulamentação Ampla',
      category: 'Livre Mercado',
      score: 9.0,
      summary: 'Dispensa total de licenças, alvarás e taxas prévias para atividades econômicas de baixo e médio risco em todo o território nacional.',
      problemStatement: 'Burocracia estatal excessiva sufoca pequenos empreendedores e incentiva a corrupção na concessão de alvarás.',
      solutionDetails: 'Princípio do livre exercício profissional com presunção de boa-fé e fiscalização posterior orientadora.',
      budgetAndCost: 'Custo Zero aos cofres públicos',
      timeline: '12 meses',
      pros: 'Aceleração na abertura de empresas e geração de empregos formais.',
      cons: 'Requer adaptação dos órgãos municipais de vigilância e zoneamento.',
      supportVotes: 1840,
      rejectVotes: 210
    },
    {
      id: 'prop-kim-3',
      title: 'Fim do Fundão Eleitoral Bilionário e Financiamento Privado Transparente',
      category: 'Reforma Política',
      score: 9.3,
      summary: 'Extinção do Fundo Especial de Financiamento de Campanha (FEFC) de R$ 5 bilhões, devolvendo o dinheiro para Saúde e Segurança.',
      problemStatement: 'Uso de verba do pagador de impostos para custear campanhas políticas e enriquecer dirigentes partidários.',
      solutionDetails: 'Campanhas financiadas exclusivamente por doações voluntárias de pessoas físicas com teto e prestação de contas diária.',
      budgetAndCost: 'Economia de R$ 4.9 bilhões por eleição',
      timeline: 'Ciclo Eleitoral 2026',
      pros: 'Fim do dreno de recursos essenciais para marketing político partidário.',
      cons: 'Oposição maciça da cúpula de grandes partidos do centro e centrão.',
      supportVotes: 2750,
      rejectVotes: 180
    }
  ],
  'cand-nikolas-ferreira': [
    {
      id: 'prop-nikolas-1',
      title: 'Projeto Escola Sem Partido e Neutralidade Ideológica',
      category: 'Educação',
      score: 8.7,
      summary: 'Vedação à doutrinação política e ideológica em sala de aula, assegurando o pluralismo de ideias e o respeito aos valores morais da família.',
      problemStatement: 'Denúncias recorrentes de viés ideológico partidário e imposição doutrinária em livros didáticos e aulas da rede pública.',
      solutionDetails: 'Fixação de cartazes com direitos dos alunos, canal de denúncias anônimo no MEC e neutralidade obrigatória do corpo docente.',
      budgetAndCost: 'R$ 15 milhões (Campanhas e Ouvidoria)',
      timeline: '12 meses',
      pros: 'Garante respeito às convicções religiosas e familiares dos estudantes.',
      cons: 'Críticas de entidades sindicais de professores sobre liberdade de cátedra.',
      supportVotes: 3120,
      rejectVotes: 1450
    },
    {
      id: 'prop-nikolas-2',
      title: 'Redução da Maioridade Penal para 16 Anos em Crimes Hediondos',
      category: 'Segurança Pública',
      score: 9.1,
      summary: 'Emenda Constitucional para julgar e punir maiores de 16 anos pelo Código Penal comum quando praticarem homicídio, estupro e latrocínio.',
      problemStatement: 'Facções criminosas cooptam menores de idade para cometer assassinatos sob a certeza da inimputabilidade penal aos 18 anos.',
      solutionDetails: 'Alteração do art. 228 da CF/88 com cumprimento em estabelecimentos prisionais separados de adultos.',
      budgetAndCost: 'R$ 350 milhões (Adaptação do sistema penitenciário)',
      timeline: '18 meses',
      pros: 'Fim da sensação de impunidade para crimes violentos de extrema gravidade.',
      cons: 'Debate jurídico no STF sobre cláusula pétrea constitucional.',
      supportVotes: 3840,
      rejectVotes: 920
    },
    {
      id: 'prop-nikolas-3',
      title: 'Garantia do Porte Legal de Arma para Defesa da Família e Agro',
      category: 'Segurança Pública',
      score: 8.6,
      summary: 'Desburocratização do acesso legal a armas de fogo para cidadãos sem antecedentes criminais e produtores rurais em áreas de fronteira e isoladas.',
      problemStatement: 'Demora e discricionariedade abusiva na concessão de registros pela Polícia Federal para moradores de áreas sem policiamento fixo.',
      solutionDetails: 'Critérios objetivos e prazos peremptórios para emissão de certidões, exame psicotécnico rigoroso e registro unificado.',
      budgetAndCost: 'Custo Zero (Auto-financiado por taxas)',
      timeline: 'Imediato',
      pros: 'Direito à legítima defesa da vida e propriedade contra invasões e assaltos rurais.',
      cons: 'Preocupações de especialistas sobre circulação de armas de grosso calibre.',
      supportVotes: 2980,
      rejectVotes: 1340
    }
  ],
  'cand-erika-hilton': [
    {
      id: 'prop-erika-1',
      title: 'PEC pelo Fim da Escala 6x1 e Semana de 4 Dias de Trabalho',
      category: 'Trabalho e Renda',
      score: 9.3,
      summary: 'Proposta de Emenda Constitucional para limitar a jornada a 36 horas semanais em 4 dias de trabalho sem redução de salários.',
      problemStatement: 'A escala 6x1 gera exaustão mental crônica (Burnout), acidentes de trabalho e destrói o convívio familiar do trabalhador.',
      solutionDetails: 'Redução gradual da jornada máxima na CLT e incentivos fiscais para empresas que adotarem o modelo de jornada reduzida.',
      budgetAndCost: 'R$ 2.4 bilhões em incentivos de transição',
      timeline: '36 meses',
      pros: 'Qualidade de vida, saúde mental e estímulo aos setores de turismo e lazer.',
      cons: 'Preocupação do comércio e serviços sobre custos operacionais de escala.',
      supportVotes: 3410,
      rejectVotes: 780
    },
    {
      id: 'prop-erika-2',
      title: 'Programa Nacional de Inclusão e Empregabilidade LGBTI+',
      category: 'Direitos Humanos',
      score: 9.0,
      summary: 'Qualificação profissional e incentivos para contratação formal de pessoas trans e travestis em empresas e órgãos públicos.',
      problemStatement: 'Mais de 90% das pessoas trans no Brasil sobrevivem na informalidade ou marginalidade por preconceito e falta de qualificação.',
      solutionDetails: 'Criação de centros de capacitação técnica, cotas em estágios públicos e selo ESG de diversidade com desoneração na folha.',
      budgetAndCost: 'R$ 180 milhões / ano',
      timeline: '24 meses',
      pros: 'Ruptura do ciclo de violência e inclusão produtiva no mercado de trabalho.',
      cons: 'Exige forte fiscalização contra fraudes em autodeclarações.',
      supportVotes: 2150,
      rejectVotes: 640
    },
    {
      id: 'prop-erika-3',
      title: 'Fortalecimento do Combate à Violência Política de Gênero e Raça',
      category: 'Cidadania',
      score: 9.2,
      summary: 'Tipificação severa e celeridade processual para crimes de ameaça, difamação e coação contra mulheres parlamentares e ativistas.',
      problemStatement: 'Crescimento de ataques orquestrados na internet e intimidação física para afastar mulheres negras e trans dos espaços de poder.',
      solutionDetails: 'Criação de protocolo de escolta da Polícia Legislativa e canal prioritário no Ministério Público Eleitoral.',
      budgetAndCost: 'R$ 45 milhões / ano',
      timeline: '12 meses',
      pros: 'Garantia do pleno exercício democrático e representatividade política.',
      cons: 'Demanda treinamento técnico de operadores de segurança em todo o país.',
      supportVotes: 1980,
      rejectVotes: 310
    }
  ],
  'cand-samia-bomfim': [
    {
      id: 'prop-samia-1',
      title: 'Taxação de Grandes Fortunas e Heranças Superiores a R$ 50 Milhões',
      category: 'Justiça Tributária',
      score: 9.1,
      summary: 'Regulamentação do Imposto sobre Grandes Fortunas (IGF) previsto na Constituição de 1988 para financiar a Saúde Pública e o SUS.',
      problemStatement: 'O Brasil possui um dos sistemas tributários mais regressivos do planeta, onde os mais pobres pagam proporcionalmente mais tributos.',
      solutionDetails: 'Alíquotas progressivas de 2% a 5% sobre patrimônios líquidos superiores a R$ 50 milhões, com combate a paraísos fiscais.',
      budgetAndCost: 'Arrecadação prevista de R$ 60 bilhões / ano',
      timeline: 'Exercício fiscal 2026',
      pros: 'Recursos massivos diretos para hospitais de alta complexidade e oncologia.',
      cons: 'Risco de fuga de capitais e repatriação patrimonial no exterior.',
      supportVotes: 2890,
      rejectVotes: 1120
    },
    {
      id: 'prop-samia-2',
      title: 'Licença-Maternidade Obrigatória de 180 Dias e Creches Integrais',
      category: 'Direitos das Mulheres',
      score: 9.4,
      summary: 'Ampliação da licença-maternidade remunerada para 6 meses para todas as trabalhadoras CLT e criação de creches públicas integrais.',
      problemStatement: 'Retorno precoce ao trabalho interrompe o aleitamento materno exclusivo e sobrecarrega financeiramente as mães trabalhadoras.',
      solutionDetails: 'Financiamento tripartite da previdência social com contrapartida de creches públicas próximas às estações de transporte.',
      budgetAndCost: 'R$ 4.2 bilhões / ano',
      timeline: '24 meses',
      pros: 'Melhores índices de desenvolvimento infantil e redução da mortalidade.',
      cons: 'Possível resistência de pequenos empregadores na contratação.',
      supportVotes: 3200,
      rejectVotes: 420
    },
    {
      id: 'prop-samia-3',
      title: 'Revogação de Isenções a Agrotóxicos e Estímulo à Agroecologia',
      category: 'Meio Ambiente',
      score: 8.9,
      summary: 'Fim dos incentivos fiscais sobre defensivos químicos perigosos e destinação dos recursos para agricultura familiar orgânica.',
      problemStatement: 'Isenção bilionária de IPI e ICMS para agrotóxicos contaminantes da água enquanto a comida orgânica permanece cara.',
      solutionDetails: 'Aplicação de alíquota cheia sobre agrotóxicos de alta toxicidade e criação de linha de crédito no Pronaf Agroecológico.',
      budgetAndCost: 'R$ 3.8 bilhões em arrecadação redirecionada',
      timeline: '18 meses',
      pros: 'Alimentação saudável, preservação dos mananciais e saúde do agricultor.',
      cons: 'Oposição da bancada ruralista e possível pressão sobre custos de commodities.',
      supportVotes: 2450,
      rejectVotes: 890
    }
  ],
  'cand-marcel-van-hattem': [
    {
      id: 'prop-marcel-1',
      title: 'Limitação de Decisões Monocráticas no STF e Fim do Foro Privilegiado',
      category: 'Reforma Institucional',
      score: 9.5,
      summary: 'PEC que proíbe liminares individuais de ministros que suspendam leis federais e extingue o foro por prerrogativa de função para políticos.',
      problemStatement: 'Ativismo judicial e decisões isoladas de magistrados atropelam o Congresso e criam blindagem para corruptos.',
      solutionDetails: 'Obrigatoriedade de deliberação colegiada para suspensão de leis e julgamento de parlamentares em 1ª instância.',
      budgetAndCost: 'Custo Zero',
      timeline: 'Imediato',
      pros: 'Restauração do equilíbrio entre os Poderes e igualdade perante a lei.',
      cons: 'Conflito institucional com o Poder Judiciário.',
      supportVotes: 3650,
      rejectVotes: 410
    },
    {
      id: 'prop-marcel-2',
      title: 'Privatização de 100% das Estatais Federais Dependentes do Tesouro',
      category: 'Desestatização',
      score: 9.2,
      summary: 'Venda de empresas públicas deficitárias e abertura total de mercado para investimentos privados em infraestrutura e logística.',
      problemStatement: 'Estatais federais acumulam prejuízos bilionários cobertos com dinheiro de impostos e servem a indicações políticas.',
      solutionDetails: 'Programa acelerado de leilões na B3 com garantia de estabilidade para serviços essenciais e incentivo à concorrência.',
      budgetAndCost: 'Receita estimada de R$ 120 bilhões',
      timeline: '48 meses',
      pros: 'Fim do rombo fiscal com estatais e atração maciça de capital estrangeiro.',
      cons: 'Resistência de sindicatos de categorias estatutárias e estatais.',
      supportVotes: 2980,
      rejectVotes: 870
    },
    {
      id: 'prop-marcel-3',
      title: 'Teto de Gastos Rígido e Proibição Constitucional de Criação de Impostos',
      category: 'Fiscal',
      score: 9.4,
      summary: 'Dispositivo constitucional impedindo o aumento da carga tributária em percentual do PIB e travamento automático de despesas em déficit.',
      problemStatement: 'Governos sucessivos aumentam gastos públicos e cobrem o rombo aumentando impostos sobre a classe produtiva.',
      solutionDetails: 'Regra de ouro fiscal: despesa pública não pode crescer acima da inflação do período anterior.',
      budgetAndCost: 'Estabilização da dívida pública',
      timeline: 'Plano Plurianual',
      pros: 'Segurança jurídica para investidores, controle inflacionário e juros baixos.',
      cons: 'Engessamento da capacidade do Estado em momentos de crise severa.',
      supportVotes: 3120,
      rejectVotes: 650
    }
  ],
  'cand-baleia-rossi': [
    {
      id: 'prop-baleia-1',
      title: 'Regulamentação e Implementação Plena da Reforma Tributária (PEC 45)',
      category: 'Tributário',
      score: 9.6,
      summary: 'Autor da PEC 45/2019 que unificou 5 impostos sobre o consumo no IVA Dual (CBS federal e IBS subnacional), simplificando a economia.',
      problemStatement: 'O manicômio tributário brasileiro consome 1.500 horas/ano de burocracia por empresa e gera R$ 5 trilhões em litígios fiscais.',
      solutionDetails: 'Criação do Comitê Gestor do IBS, cesta básica nacional 100% desonerada e cashback de impostos para famílias do Cadastro Único.',
      budgetAndCost: 'Custo de implantação R$ 400M (Sistemas de TI integrados)',
      timeline: '2026 - 2033 (Período de transição)',
      pros: 'Aumento previsto de 12% a 20% no PIB brasileiro em 15 anos.',
      cons: 'Complexidade na calibragem das alíquotas de referência durante a transição.',
      supportVotes: 2540,
      rejectVotes: 320
    },
    {
      id: 'prop-baleia-2',
      title: 'Fundo Nacional de Infraestrutura Logística e Hidrovias',
      category: 'Transporte e Agro',
      score: 9.0,
      summary: 'Criação de fundo público-privado para viabilizar duplicações de rodovias de escoamento e dragagem de hidrovias no interior paulista.',
      problemStatement: 'Gargalos logísticos encarecem o frete em até 30%, prejudicando o produtor nacional na exportação de grãos e manufaturados.',
      solutionDetails: 'Parcerias Público-Privadas (PPPs) com debêntures incentivadas para corredores de exportação hidroviários.',
      budgetAndCost: 'R$ 8.5 bilhões (Fundo Misto)',
      timeline: '48 meses',
      pros: 'Redução drástica do custo Brasil e menor emissão de carbono por tonelada transportada.',
      cons: 'Dependência de licenças ambientais em bacias hidrográficas interestaduais.',
      supportVotes: 1890,
      rejectVotes: 180
    },
    {
      id: 'prop-baleia-3',
      title: 'Desoneração e Fortalecimento da Atenção Básica de Saúde Municipal',
      category: 'Saúde Pública',
      score: 8.9,
      summary: 'Repasse direto Fundo a Fundo para Unidades Básicas de Saúde (UBS) e aumento do teto MAC para Santas Casas de Misericórdia.',
      problemStatement: 'Santas Casas acumulam dívidas históricas operando procedimentos de alta complexidade com tabela SUS defasada.',
      solutionDetails: 'Reajuste da tabela SUS para procedimentos hospitalares essenciais e repasse sem intermediários para municípios conveniados.',
      budgetAndCost: 'R$ 6.2 bilhões / ano',
      timeline: '24 meses',
      pros: 'Socorro imediato aos hospitais filantrópicos que realizam mais de 50% dos partos SUS.',
      cons: 'Exige remanejamento orçamentário no Ministério da Saúde.',
      supportVotes: 2210,
      rejectVotes: 95
    }
  ],
  'cand-gleisi-hoffmann': [
    {
      id: 'prop-gleisi-1',
      title: 'Isenção Total de Imposto de Renda para Trabalhadores até R$ 5.000',
      category: 'Economia Popular',
      score: 9.4,
      summary: 'Atualização da tabela do IRPF para isentar quem ganha até 3,5 salários mínimos, compensando com tributação de super-ricos.',
      problemStatement: 'A defasagem histórica da tabela do IR penaliza a classe média assalariada, que paga impostos acima de bilionários.',
      solutionDetails: 'Elevação da faixa de isenção para R$ 5.000 mensais com alíquotas mais altas sobre dividendos e lucros no topo da pirâmide.',
      budgetAndCost: 'R$ 35 bilhões (Compensado com taxação de lucros e dividendos)',
      timeline: 'Exercício 2026',
      pros: 'Injeção direta de renda no bolso de mais de 10 milhões de trabalhadores.',
      cons: 'Resistência de setores do mercado financeiro e investidores individuais.',
      supportVotes: 3620,
      rejectVotes: 890
    },
    {
      id: 'prop-gleisi-2',
      title: 'Expansão do Minha Casa Minha Vida com Financiamento a Juros Zero',
      category: 'Habitação',
      score: 9.2,
      summary: 'Subsídio integral de moradias para famílias com renda de até 2 salários mínimos e requalificação de prédios públicos abandonados.',
      problemStatement: 'Déficit habitacional de 6 milhões de famílias nas grandes regiões metropolitanas convive com imóveis públicos ociosos.',
      solutionDetails: 'Contratação de 2 milhões de novas unidades subsidiadas e retrofits em centros urbanos consolidados.',
      budgetAndCost: 'R$ 14 bilhões / ano',
      timeline: '36 meses',
      pros: 'Geração imediata de vagas na construção civil e dignidade familiar.',
      cons: 'Risco de atrasos em obras por reajustes de insumos como cimento e aço.',
      supportVotes: 3150,
      rejectVotes: 610
    },
    {
      id: 'prop-gleisi-3',
      title: 'Retomada de Grandes Obras Estruturantes e Reindustrialização (Novo PAC)',
      category: 'Indústria e Emprego',
      score: 9.0,
      summary: 'Aporte massivo em ferrovias, transição ecológica e complexo econômico da saúde para reduzir a dependência externa de insumos.',
      problemStatement: 'Desindustrialização precoce do Brasil nas últimas décadas transformou o país em mero exportador de commodities brutas.',
      solutionDetails: 'Financiamento a juros competitivos via BNDES com exigência de conteúdo local e sustentabilidade ambiental.',
      budgetAndCost: 'R$ 45 bilhões (Capitais mistos)',
      timeline: '48 meses',
      pros: 'Empregos de alta qualificação e soberania tecnológica nacional.',
      cons: 'Monitoramento rígido do TCU para evitar sobrepreço e aditivos contratuais.',
      supportVotes: 2780,
      rejectVotes: 730
    }
  ],
  'cand-luiza-erundina': [
    {
      id: 'prop-erundina-1',
      title: 'Tarifa Zero no Transporte Público Urbano para Toda a População',
      category: 'Mobilidade Urbana',
      score: 9.5,
      summary: 'Pioneira da tese no Brasil, propõe financiamento do transporte coletivo gratuito municipal mediante fundos públicos solidários.',
      problemStatement: 'O custo da passagem consome até 25% da renda do trabalhador periférico, criando segregação espacial e desemprego.',
      solutionDetails: 'Substituição da tarifa na catraca por taxa de mobilidade empresarial e uso de receitas de multas de trânsito e estacionamentos.',
      budgetAndCost: 'R$ 12 bilhões / ano nas metrópoles',
      timeline: 'Implementação progressiva em 3 anos',
      pros: 'Democratização do direito à cidade, redução de carros e menor poluição do ar.',
      cons: 'Exige reestruturação orçamentária expressiva das prefeituras.',
      supportVotes: 3890,
      rejectVotes: 980
    },
    {
      id: 'prop-erundina-2',
      title: 'Estatuto dos Conselhos Populares e Orçamento Participativo Obrigatório',
      category: 'Democracia Direta',
      score: 9.1,
      summary: 'Obrigatoriedade de deliberação popular em bairros e comunidades sobre pelo menos 15% dos investimentos municipais e estaduais.',
      problemStatement: 'Obras públicas decididas em gabinetes fechados frequentemente ignoram as prioridades reais de saneamento e creches das vilas.',
      solutionDetails: 'Plataformas digitais cívicas aliadas a assembleias comunitárias vinculantes para priorização de obras públicas.',
      budgetAndCost: 'R$ 80 milhões (Plataformas e mediação)',
      timeline: '18 meses',
      pros: 'Empoderamento comunitário e combate direto ao clientelismo político.',
      cons: 'Pode alongar o prazo inicial de aprovação dos projetos de engenharia.',
      supportVotes: 2450,
      rejectVotes: 380
    },
    {
      id: 'prop-erundina-3',
      title: 'Comissão Permanente da Verdade e Reparação Histórica',
      category: 'Direitos Humanos',
      score: 9.3,
      summary: 'Fortalecimento das políticas de memória, verdade e justiça com abertura irrevogável de todos os arquivos militares e civis do regime autoritário.',
      problemStatement: 'A impunidade de crimes de Estado alimenta arroubos golpistas e desrespeito aos direitos fundamentais no presente.',
      solutionDetails: 'Digitalização com IA de documentos confidenciais de arquivos públicos e inserção obrigatória de educação cívica nos currículos.',
      budgetAndCost: 'R$ 35 milhões',
      timeline: '24 meses',
      pros: 'Consolidação definitiva do pacto democrático brasileiro.',
      cons: 'Reação contrária de setores saudosistas e militares da reserva.',
      supportVotes: 2190,
      rejectVotes: 870
    }
  ],
  'cand-duda-salabert': [
    {
      id: 'prop-duda-1',
      title: 'Proteção da Serra do Curral e Proibição de Mineração em Mananciais',
      category: 'Meio Ambiente',
      score: 9.6,
      summary: 'Tombamento nacional e proteção definitiva da Serra do Curral e bacias hidrográficas contra projetos predatórios de mineração.',
      problemStatement: 'A mineração irresponsável ameaça o abastecimento de água potável de mais de 5 milhões de mineiros na Grande BH.',
      solutionDetails: 'Criação do Parque Nacional da Serra do Curral e endurecimento de penalidades para mineradoras que degradem aquíferos.',
      budgetAndCost: 'R$ 250 milhões (Fundo de Compensação Ambiental)',
      timeline: 'Imediato',
      pros: 'Segurança hídrica para as próximas gerações e preservação de patrimônio natural.',
      cons: 'Pressão econômica de mineradoras sobre arrecadação de royalties (CFEM).',
      supportVotes: 3250,
      rejectVotes: 410
    },
    {
      id: 'prop-duda-2',
      title: 'Piso Salarial Nacional do Magistério Pago com Transferência Direta',
      category: 'Educação',
      score: 9.4,
      summary: 'Complementação da União para garantir que nenhum estado ou município pague aos professores menos que o piso nacional de R$ 4.580.',
      problemStatement: 'Professores em milhares de municípios continuam ganhando abaixo do piso por alegação de falta de dotação orçamentária local.',
      solutionDetails: 'Aporte federal automático via Fundeb para entes federados que comprovarem limite de responsabilidade fiscal.',
      budgetAndCost: 'R$ 5.6 bilhões / ano',
      timeline: '12 meses',
      pros: 'Valorização real da carreira docente e atração de jovens talentos para o magistério.',
      cons: 'Necessidade de auditar as folhas de pagamento de milhares de cidades.',
      supportVotes: 3600,
      rejectVotes: 280
    },
    {
      id: 'prop-duda-3',
      title: 'Fundo Nacional Solar Popular para Famílias de Baixa Renda',
      category: 'Transição Energética',
      score: 9.1,
      summary: 'Instalação gratuita de painéis solares nos telhados de moradias populares para zerar a conta de luz dos mais vulneráveis.',
      problemStatement: 'A tarifa de energia elétrica consome fatia desproporcional do orçamento de famílias que ganham até 2 salários mínimos.',
      solutionDetails: 'Financiamento através da taxa setorial de P&D das distribuidoras de energia com instalação por técnicos locais capacitados.',
      budgetAndCost: 'R$ 2.8 bilhões / ano',
      timeline: '36 meses',
      pros: 'Geração de energia limpa distribuída e alívio financeiro imediato.',
      cons: 'Manutenção preventiva dos equipamentos em áreas com telhados precários.',
      supportVotes: 2980,
      rejectVotes: 190
    }
  ],
  'cand-marco-feliciano': [
    {
      id: 'prop-feliciano-1',
      title: 'Estatuto do Nascituro e Vedação Constitucional Irrestrita ao Aborto',
      category: 'Valores e Família',
      score: 8.8,
      summary: 'Garantia legal dos direitos de personalidade, proteção à vida e herança ao ser humano concebido desde o momento da fecundação.',
      problemStatement: 'Movimentos judiciais no STF tentam legalizar o aborto sem passar pela deliberação dos representantes eleitos pelo povo.',
      solutionDetails: 'Inserção do direito à vida desde a concepção no art. 5º da CF/88 e fortalecimento das redes de apoio e adoção ágil de bebês.',
      budgetAndCost: 'R$ 120 milhões (Redes de acolhimento e adoção)',
      timeline: 'Imediato',
      pros: 'Proteção irrestrita aos mais indefesos e estímulo à adoção célere.',
      cons: 'Debate acirrado com coletivos de direitos reprodutivos e saúde pública.',
      supportVotes: 3410,
      rejectVotes: 1650
    },
    {
      id: 'prop-feliciano-2',
      title: 'Proteção Constitucional da Liberdade Religiosa e Isenção de Templos',
      category: 'Liberdade Religiosa',
      score: 9.0,
      summary: 'Blindagem contra qualquer intervenção do Estado na pregação moral, cultos e atuação social e de recuperação das igrejas de qualquer credo.',
      problemStatement: 'Tentativas de responsabilização criminal de líderes religiosos por pregações baseadas em textos sagrados tradicionais.',
      solutionDetails: 'Imunidade tributária plena para templos e garantia da capelania hospitalar e prisional sem entraves estatais.',
      budgetAndCost: 'Custo Zero',
      timeline: 'Imediato',
      pros: 'Garantia fundamental da liberdade de consciência, crença e culto.',
      cons: 'Cobrança da sociedade civil sobre transparência financeira de megaigrejas.',
      supportVotes: 3120,
      rejectVotes: 1210
    },
    {
      id: 'prop-feliciano-3',
      title: 'Apoio a Comunidades Terapêuticas de Recuperação de Dependentes Químicos',
      category: 'Segurança e Saúde',
      score: 8.9,
      summary: 'Destinação prioritária de verbas da Senad para entidades da sociedade civil que acolhem e recuperam dependentes de crack e álcool.',
      problemStatement: 'Cracolândias se proliferam nas capitais enquanto o poder público insiste em modelos de redução de danos sem internação.',
      solutionDetails: 'Contratos de gestão com comunidades terapêuticas credenciadas com acolhimento voluntário e reinserção ao trabalho.',
      budgetAndCost: 'R$ 650 milhões / ano',
      timeline: '24 meses',
      pros: 'Resgate humanizado de dependentes químicos e pacificação de áreas urbanas degradadas.',
      cons: 'Críticas de associações de psiquiatria que defendem modelos baseados em CAPS.',
      supportVotes: 2850,
      rejectVotes: 890
    }
  ],
  'cand-mario-frias': [
    {
      id: 'prop-frias-1',
      title: 'Auditoria Rigorosa e Teto Máximo de Captação na Lei Rouanet',
      category: 'Cultura e Transparência',
      score: 9.1,
      summary: 'Redução drástica do limite de captação individual por projeto e auditoria com inteligência artificial sobre notas fiscais de incentivos culturais.',
      problemStatement: 'Concentração de milhões em poucos artistas consagrados enquanto a cultura popular de pequenas cidades é desprovida de verbas.',
      solutionDetails: 'Teto de R$ 500 mil por projeto e obrigatoriedade de 50% dos ingressos gratuitos para escolas públicas e asilos.',
      budgetAndCost: 'Economia fiscal e descentralização para 5.000 municípios',
      timeline: 'Imediato',
      pros: 'Fim do corporativismo de grandes produtoras e valorização do pequeno artista.',
      cons: 'Dificuldade de viabilização de megamusicais internacionais.',
      supportVotes: 2950,
      rejectVotes: 780
    },
    {
      id: 'prop-frias-2',
      title: 'Descentralização de Recursos Culturais para Tradições Regionais e Folclore',
      category: 'Cultura Nacional',
      score: 8.8,
      summary: 'Criação do Circuito Cultural Brasileiro com fomento a feiras de artesanato, bandas marciais, música sertaneja de raiz e teatro sacro.',
      problemStatement: 'As manifestações culturais que expressam a verdadeira identidade do povo brasileiro sofriam boicote histórico em editais centrais.',
      solutionDetails: 'Editais simplificados geridos diretamente com secretarias municipais de cidades com menos de 100 mil habitantes.',
      budgetAndCost: 'R$ 380 milhões / ano',
      timeline: '24 meses',
      pros: 'Preservação da memória histórica e resgate do orgulho das tradições patrióticas.',
      cons: 'Demanda treinamento técnico de secretários municipais de cultura.',
      supportVotes: 2410,
      rejectVotes: 520
    },
    {
      id: 'prop-frias-3',
      title: 'Proteção Irrestrita da Liberdade de Opinião e Vedação à Censura Digital',
      category: 'Liberdade de Expressão',
      score: 9.2,
      summary: 'Garantia de que opiniões políticas, artísticas ou jornalísticas não sejam desmonetizadas ou banidas de plataformas sem ordem de juiz natural.',
      problemStatement: 'Inquéritos secretos e moderação ideológica de big techs censurando influenciadores e cidadãos comuns.',
      solutionDetails: 'Multas severas para plataformas que removerem contas ou conteúdos de opinião sem contraditório prévio.',
      budgetAndCost: 'Custo Zero',
      timeline: 'Imediato',
      pros: 'Manutenção do debate público livre e sem amarras burocráticas estatais.',
      cons: 'Debate sobre o equilíbrio entre liberdade de expressão e moderação de fake news.',
      supportVotes: 2890,
      rejectVotes: 820
    }
  ],
  'cand-luiz-philippe': [
    {
      id: 'prop-luiz-1',
      title: 'Nova Constituição Descentralizadora com Federalismo Pleno',
      category: 'Reforma Constitucional',
      score: 9.5,
      summary: 'Reestruturação federativa para que 70% da arrecadação tributária permaneça diretamente nos municípios e estados, enfraquecendo Brasília.',
      problemStatement: 'O modelo de Brasília concentra poder e dinheiro, obrigando prefeitos e governadores a mendigar verbas em troca de apoio político.',
      solutionDetails: 'Competência tributária e legislativa descentralizada nos moldes dos estados norte-americanos e cantões suíços.',
      budgetAndCost: 'Reforma estrutural de pacto federativo',
      timeline: 'Nova Assembleia Constituinte',
      pros: 'Fim do toma-lá-dá-cá em Brasília e governança muito mais próxima do cidadão.',
      cons: 'Exige consenso nacional e quebra de resistências da burocracia central federal.',
      supportVotes: 2880,
      rejectVotes: 540
    },
    {
      id: 'prop-luiz-2',
      title: 'Voto Distrital Puro e Mecanismo de Recall de Mandatos Eletivos',
      category: 'Reforma Política',
      score: 9.3,
      summary: 'Divisão dos estados em distritos eleitorais onde o candidato mais votado assume, com possibilidade do eleitor revogar o mandato no meio do termo.',
      problemStatement: 'No sistema proporcional atual, candidatos com poucos votos são eleitos puxados por celebridades e o eleitor não sabe quem o representa.',
      solutionDetails: 'Cada deputado responde a um distrito geográfico delimitado e pode ser destituído se 20% do eleitorado assinar petição de recall.',
      budgetAndCost: 'R$ 150 milhões (Ajuste das zonas pela Justiça Eleitoral)',
      timeline: 'Eleições 2030',
      pros: 'Representatividade autêntica, fiscalização direta de bairro e redução de custos de campanha.',
      cons: 'Pode prejudicar minorias dispersas geograficamente pelo território.',
      supportVotes: 2750,
      rejectVotes: 390
    },
    {
      id: 'prop-luiz-3',
      title: 'Autonomia Orçamentária e Fim da Vinculação Obrigatória de Receitas',
      category: 'Finanças Públicas',
      score: 9.0,
      summary: 'Desvinculação total das receitas da União, permitindo aos gestores eleitos aplicar os recursos onde a demanda do momento exigir.',
      problemStatement: 'Mais de 94% do orçamento federal é engessado por vinculações obrigatórias, impedindo qualquer ajuste fiscal sem corte de investimentos.',
      solutionDetails: 'Flexibilização gradual com prestação de contas dos resultados e responsabilização fiscal dos gestores.',
      budgetAndCost: 'Desengessamento de R$ 800 bilhões do orçamento',
      timeline: '48 meses',
      pros: 'Maior responsabilidade dos governantes e eficiência no uso do dinheiro público.',
      cons: 'Temor de setores da Saúde e Educação sobre perda de pisos constitucionais.',
      supportVotes: 2310,
      rejectVotes: 810
    }
  ],
  'cand-celia-xakriaba': [
    {
      id: 'prop-celia-1',
      title: 'Demarcação Imediata de Terras Indígenas e Proteção do Bioma Cerrado',
      category: 'Meio Ambiente',
      score: 9.6,
      summary: 'Conclusão dos processos demarcatórios pendentes e reconhecimento do Cerrado como Patrimônio Nacional na Constituição Federal.',
      problemStatement: 'O Cerrado, berço das águas do Brasil, perde vegetação nativa em ritmo alarmante, secando nascentes e expulsando comunidades.',
      solutionDetails: 'Homologação célere de laudos antropológicos da Funai e fortalecimento da fiscalização do Ibama com apoio das brigadas indígenas.',
      budgetAndCost: 'R$ 480 milhões / ano',
      timeline: '24 meses',
      pros: 'Preservação de aquíferos vitais, barreira natural contra o aquecimento global e justiça histórica.',
      cons: 'Conflitos fundiários com fazendeiros e posseiros na fronteira agrícola.',
      supportVotes: 3100,
      rejectVotes: 780
    },
    {
      id: 'prop-celia-2',
      title: 'Fundo Climático Gerido pelos Povos Originários contra o Desmatamento',
      category: 'Clima e Sustentabilidade',
      score: 9.3,
      summary: 'Criação de fundo de pagamento por serviços ambientais pago diretamente a aldeias e comunidades tradicionais que mantêm a floresta em pé.',
      problemStatement: 'Terras indígenas são as áreas mais preservadas do país, mas as comunidades não recebem contrapartida financeira para sua subsistência.',
      solutionDetails: 'Captação de recursos de créditos de carbono no mercado global com repasse direto para projetos de bioeconomia e reflorestamento.',
      budgetAndCost: 'US$ 500 milhões (Captação internacional)',
      timeline: '36 meses',
      pros: 'Geração de renda sustentável e reconhecimento da soberania ambiental originária.',
      cons: 'Exige governança rigorosa para evitar intermediários predatórios no mercado de carbono.',
      supportVotes: 2890,
      rejectVotes: 420
    },
    {
      id: 'prop-celia-3',
      title: 'Inclusão Curricular Obrigatória dos Saberes e Línguas Ancestrais Indígenas',
      category: 'Educação e Cultura',
      score: 9.1,
      summary: 'Implementação efetiva da Lei 11.645 em todas as escolas com formação continuada de educadores e contratação de professores indígenas.',
      problemStatement: 'A história do Brasil continua sendo ensinada com apagamento da memória, das línguas e da cosmovisão dos povos originários.',
      solutionDetails: 'Produção de material didático bilingue, publicação de literatura indígena e criação de cotas para mestres tradicionais em universidades.',
      budgetAndCost: 'R$ 140 milhões / ano',
      timeline: '24 meses',
      pros: 'Superação do racismo estrutural e enriquecimento cultural de toda a sociedade.',
      cons: 'Déficit de materiais didáticos aprovados em certas línguas de menor difusão.',
      supportVotes: 2580,
      rejectVotes: 310
    }
  ],
  'cand-chico-alencar': [
    {
      id: 'prop-chico-1',
      title: 'Fim do Orçamento Secreto e Vedação Constitucional de Emendas sem Transparência',
      category: 'Ética Pública',
      score: 9.7,
      summary: 'Proibição definitiva de emendas Pix e de relator sem identificação do autor, projeto executivo aprovado e fiscalização em tempo real pelo TCU.',
      problemStatement: 'Dezenas de bilhões de reais de emendas parlamentares foram distribuídos sem critérios técnicos, alimentando corrupção eleitoreira.',
      solutionDetails: 'Plataforma pública obrigatória com rastreamento por geolocalização e fotos da execução de cada centavo empenhado.',
      budgetAndCost: 'Economia e direcionamento ético de R$ 35 bilhões / ano',
      timeline: 'Imediato',
      pros: 'Restauração da moralidade republicana e fim do balcão de negócios eleitoral.',
      cons: 'Forte resistência do establishment parlamentar viciado em repasses opacos.',
      supportVotes: 4120,
      rejectVotes: 320
    },
    {
      id: 'prop-chico-2',
      title: 'Reforma Política com Paridade de Gênero e Financiamento Democrático',
      category: 'Reforma Política',
      score: 9.2,
      summary: 'Obrigatoriedade de listas partidárias preordenadas com alternância de sexo (50% mulheres) e limites severos de doações empresariais indiretas.',
      problemStatement: 'O Congresso brasileiro tem menos de 18% de representação feminina, apesar de as mulheres serem a maioria da população.',
      solutionDetails: 'Sistema eleitoral proporcional misto com listas zipadas (homem/mulher sucessivamente) em todos os níveis.',
      budgetAndCost: 'Custo Zero',
      timeline: 'Eleições 2026',
      pros: 'Democracia verdadeiramente representativa e reflexo real do povo brasileiro.',
      cons: 'Oposição de cúpulas partidárias masculinas tradicionais.',
      supportVotes: 2950,
      rejectVotes: 740
    },
    {
      id: 'prop-chico-3',
      title: 'Auditoria Cidadã da Dívida Pública e Priorização da Seguridade Social',
      category: 'Economia e Direitos',
      score: 9.0,
      summary: 'Auditoria completa da dívida pública interna e externa para identificar ilegitimidades e garantir que os juros não sangrem a Saúde e Educação.',
      problemStatement: 'O pagamento de juros e amortizações da dívida consome quase 40% do orçamento da União, beneficiando especuladores.',
      solutionDetails: 'Criação de comissão mista permanente no Congresso com participação de economistas da sociedade civil e sindicatos.',
      budgetAndCost: 'R$ 20 milhões (Estrutura da auditoria)',
      timeline: '18 meses',
      pros: 'Transparência nas finanças soberanas e proteção das conquistas da seguridade social.',
      cons: 'Críticas de agentes do mercado sobre risco de desconfiança na rolagem dos títulos públicos.',
      supportVotes: 2680,
      rejectVotes: 890
    }
  ]
};

module.exports = { REAL_PROPOSALS };
